### PR TITLE
Fix flow error in reduceAssertionObject

### LINKED ISSUE #219: Flow error on missing import type
There's a flow error here:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/enzyme-matchers/lib/utils/reduceAssertionObject.js.flow:6:10

Cannot import the type ObjectReductionResponse as a value. Use import type instead.

     3│  */
     4│
     5│ import deepEqualIdent from 'deep-equal-ident';
     6│ import { ObjectReductionResponse } from '../types';
     7│
     8│ type ObjectKey = Object | string;
     9│



Found 1 error
error An unexpected error occurred: "Command failed.
```

### PR DESCRIPTION
**Pull request by fernandopasik**
fixes #219

### CODE REVIEW

**Comment by blainekasten** [comment]
Thanks @fernandopasik and thanks @pascalduez for the review!

**Comment by pascalduez** [comment]
@blainekasten could you please release a patch? That breaks my release process :)
Would be super rad.

**Comment by blainekasten** [comment]
@pascalduez sure thing, 1s

**Comment by fernandopasik** [comment]
You are welcome @blainekasten!

**Pull request merged**
