### PR TITLE
Release 5.0.3

### PR DESCRIPTION
**Pull request by blainekasten**
🎉 Thanks @fernandopasik 🎉

### CODE REVIEW

**Comment by blainekasten** [comment]
cc @pascalduez (it's already live)

**Comment by pascalduez** [comment]
@blainekasten Thanks a lot!

**Comment by pascalduez** [comment]
@blainekasten BTW https://github.com/flowtype/flow-typed/pull/1932

**Comment by blainekasten** [comment]
@pascalduez Awesome! Glad to know you use flow so properly!

**Pull request merged**
