### PR TITLE
Clarify usage with TypeScript

### PR DESCRIPTION
**Pull request by lostfictions**
Following discussion in #258, I've amended the readme to include the extra necessary step for usage with TypeScript.

### CODE REVIEW

**Comment by blainekasten** [comment]
Can you squash these down to 1 commit with a better commit message for me? Thanks so much for the contribution!

**Comment by lostfictions** [comment]
@blainekasten just did it in the in-browser editor -- could you just do a squash merge? otherwise i'll clone it down and squash.

**Comment by lostfictions** [comment]
nevermind -- fixed!

**Comment by blainekasten** [comment]
You're the best :) Thanks!

**Pull request merged**
