### PR TITLE
upgrade jest-environment-jsdom to 24 to resolve braces security advisory

### PR DESCRIPTION
**Pull request by tgaff**
See #295 (and #296 #297 )
Root Yarn.lock also updated which I think was missed in #297.  (Feel free to credit one of the other users on that.)

Note:  I noticed the older version of braces still shows in an individual package `yarn.lock` file.  I don't have any experience with lerna but I tried to figure out how lerna uses those and I think the answer is that it doesn't.  Those files look like they haven't been updated since their creation.  I'm opening another PR to remove them.

### CODE REVIEW

**Comment by blainekasten** [comment]
Thanks @tgaff !

**Comment by tgaff** [comment]
Thanks!  Do you think you'll do a release for this soon?  
I think people looking for it are all just trying to get past an automated security alert.  This was the last package in one of our repos that I was unable to just upgrade outright.

**Comment by blainekasten** [comment]
@tgaff sorry, i've been very busy lately. I will get this done this week. Maybe today, likely tomorrow

**Comment by tgaff** [comment]
thanks a ton!

**Comment by blainekasten** [comment]
7.0.2 is releases with a fix!

**Comment by tgaff** [comment]
Thanks!

**Pull request merged**
