### PR TITLE
Ignore whitespaces between tags by toHaveHTML

### LINKED ISSUE #246: Ignore whitespaces between tags by toHaveHTML
At the moment, one has to write:

```js
expect(component).toHaveHTML('<div class="row"><div class="col-1"><div class="tile"><div class="label">Label line</div><div class="content">Value line</div><div class="footnote">Footnote line</div></div></div></div>');
```

It would be really nice if this could be expanded in a more readable form and let the assertion ignore the blanks between tags:

```js
expect(component).toHaveHTML(
  `<div class="row">
    <div class="col-1">
      <div class="tile">
        <div class="label">Label line</div>
        <div class="content">Value line</div>
        <div class="footnote">Footnote line</div>
      </div>
    </div>
  </div>`
);
```

I have this change locally and it works well, haven't noticed any downsides so far, so happy to turn it into a PR if you are open to that.

(I cannot use something like:
```js
expect(component).toHaveHTML(
  '<div class="row">' +
    '<div class="col-1">' +
      /* ... */
```
because automated formatters such as [Prettier](https://prettier.io/) reformat this accordingly.)

### PR DESCRIPTION
**Pull request by astorije**
This makes passing multiline strings possible.

Resolves #246, see this issue for example of what this can do.

### CODE REVIEW

**Comment by blainekasten** [comment]
Thanks @astorije I'll try to release a new version tomorrow!

**Comment by astorije** [comment]
That's awesome, thanks @blainekasten!

**Comment by astorije** [comment]
Hey @blainekasten, any news on release? :)

**Comment by blainekasten** [comment]
@astorije Sorry for the delay!

https://github.com/FormidableLabs/enzyme-matchers/releases/tag/v6.0.3

(also, happy to see another rock climber in the tech scene!)

**Comment by astorije** [comment]
Perfect, thanks @blainekasten! And yep, when I'm not stuck at work at night debugging stupid bugs I left in our tests, you'll likely see me in a climbing gym somewhere! If you're ever in the Boston area, reach out to me :)

**Pull request merged**
